// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc-_XvGBGW_pkqz9enFtDOADbnwQcp--A',
    appId: '1:368641058862:web:92fd99610749b7ed4d97bf',
    messagingSenderId: '368641058862',
    projectId: 'simple-tools-3e1db',
    authDomain: 'simple-tools-3e1db.firebaseapp.com',
    databaseURL: 'https://simple-tools-3e1db.firebaseio.com',
    storageBucket: 'simple-tools-3e1db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgLplHSKK98fCZvgD-Ag2vHeT0JF4FCwk',
    appId: '1:368641058862:android:852a71d75b2360ed',
    messagingSenderId: '368641058862',
    projectId: 'simple-tools-3e1db',
    databaseURL: 'https://simple-tools-3e1db.firebaseio.com',
    storageBucket: 'simple-tools-3e1db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHJJU8V4eFW0kwZo9q46E_hB2HwdZK60',
    appId: '1:368641058862:ios:cdcfb0d3317f3fa64d97bf',
    messagingSenderId: '368641058862',
    projectId: 'simple-tools-3e1db',
    databaseURL: 'https://simple-tools-3e1db.firebaseio.com',
    storageBucket: 'simple-tools-3e1db.appspot.com',
    androidClientId: '368641058862-gn3o3s5or867jdcjvg7760u32c6lshgt.apps.googleusercontent.com',
    iosClientId: '368641058862-4gcomh6lsnd1uvcb6s4vvg4ch6jionaj.apps.googleusercontent.com',
    iosBundleId: 'com.ahsailabs.simpletools',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYHJJU8V4eFW0kwZo9q46E_hB2HwdZK60',
    appId: '1:368641058862:ios:cdcfb0d3317f3fa64d97bf',
    messagingSenderId: '368641058862',
    projectId: 'simple-tools-3e1db',
    databaseURL: 'https://simple-tools-3e1db.firebaseio.com',
    storageBucket: 'simple-tools-3e1db.appspot.com',
    androidClientId: '368641058862-gn3o3s5or867jdcjvg7760u32c6lshgt.apps.googleusercontent.com',
    iosClientId: '368641058862-4gcomh6lsnd1uvcb6s4vvg4ch6jionaj.apps.googleusercontent.com',
    iosBundleId: 'com.ahsailabs.simpletools',
  );
}
